version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  django:
    build: .
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    environment:
      # для settings.py
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "change-me"
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
